name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: |
        dotnet test --no-restore --verbosity normal
        dotnet run < examples/a-plus-b.ml
        dotnet run < examples/nested-functions.ml
        dotnet run < examples/nested-functions-with-free-variables.ml
