name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Setup OCaml
      run: sudo apt install ocaml

    - name: Test
      run: |
        dotnet test --no-restore --verbosity normal
        for f in examples/*.ml ; do
            dotnet run < $f > $f.actual
            ocaml <(echo 'print_int(' ; cat $f ; echo ');print_newline()') > $f.expected
            diff $f.actual $f.expected || exit 1
        done
